const dailyQuotes = {
    "1-1": { quote: "The journey of a thousand miles begins with one step.", author: "Lao Tzu" },
    "1-2": { quote: "Whatever you are, be a good one.", author: "Abraham Lincoln" },
    "1-3": { quote: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
    "1-4": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "1-5": { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    "1-6": { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    "1-7": { quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford" },
    "1-8": { quote: "Act as if what you do makes a difference. It does.", author: "William James" },
    "1-9": { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    "1-10": { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    // January 11th to 31st
    "1-11": { quote: "Change your thoughts and you change your world.", author: "Norman Vincent Peale" },
    "1-12": { quote: "Happiness is not something ready made. It comes from your own actions.", author: "Dalai Lama" },
    "1-13": { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    "1-14": { quote: "Perseverance is not a long race; it is many short races one after the other.", author: "Walter Elliot" },
    "1-15": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    "1-16": { quote: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
    "1-17": { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    "1-18": { quote: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
    "1-19": { quote: "You define your own life. Don’t let other people write your script.", author: "Oprah Winfrey" },
    "1-20": { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    "1-21": { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    "1-22": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "1-23": { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    "1-24": { quote: "I am not a product of my circumstances. I am a product of my decisions.", author: "Stephen Covey" },
    "1-25": { quote: "The most common way people give up their power is by thinking they don’t have any.", author: "Alice Walker" },
    "1-26": { quote: "An unexamined life is not worth living.", author: "Socrates" },
    "1-27": { quote: "Do what is right, not what is easy nor what is popular.", author: "Roy T. Bennett" },
    "1-28": { quote: "Your time is limited, don’t waste it living someone else’s life.", author: "Steve Jobs" },
    "1-29": { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    "1-30": { quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
    "1-31": { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },

    // February 1st to 28th
    "2-1": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "2-2": { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    "2-3": { quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson" },
    "2-4": { quote: "Go confidently in the direction of your dreams! Live the life you've imagined.", author: "Henry David Thoreau" },
    "2-5": { quote: "Happiness is not by chance, but by choice.", author: "Jim Rohn" },
    "2-6": { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    "2-7": { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    "2-8": { quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair" },
    "2-9": { quote: "You only live once, but if you do it right, once is enough.", author: "Mae West" },
    "2-10": { quote: "Failure is not the opposite of success; it’s part of success.", author: "Arianna Huffington" },
    "2-11": { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    "2-12": { quote: "Do what you feel in your heart to be right – for you’ll be criticized anyway.", author: "Eleanor Roosevelt" },
    "2-13": { quote: "The purpose of our lives is to be happy.", author: "Dalai Lama" },
    "2-14": { quote: "Love the life you live. Live the life you love.", author: "Bob Marley" },
    "2-15": { quote: "Don’t wait. The time will never be just right.", author: "Napoleon Hill" },
    "2-16": { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    "2-17": { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    "2-18": { quote: "What we think, we become.", author: "Buddha" },
    "2-19": { quote: "You can waste your lives drawing lines. Or you can live your life crossing them.", author: "Shonda Rhimes" },
    "2-20": { quote: "Life isn’t about finding yourself. Life is about creating yourself.", author: "George Bernard Shaw" },
    "2-21": { quote: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
    "2-22": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "2-23": { quote: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
    "2-24": { quote: "Our lives begin to end the day we become silent about things that matter.", author: "Martin Luther King Jr." },
    "2-25": { quote: "There is no substitute for hard work.", author: "Thomas Edison" },
    "2-26": { quote: "Don’t be pushed by your problems. Be led by your dreams.", author: "Ralph Waldo Emerson" },
    "2-27": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "2-28": { quote: "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.", author: "Dr. Seuss" },

    // March 1st to 31st
    "3-1": { quote: "Your life does not get better by chance, it gets better by change.", author: "Jim Rohn" },
    "3-2": { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    "3-3": { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    "3-4": { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
    "3-5": { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    "3-6": { quote: "Difficulties in life are intended to make us better, not bitter.", author: "Dan Reeves" },
    "3-7": { quote: "The best preparation for tomorrow is doing your best today.", author: "H. Jackson Brown, Jr." },
    "3-8": { quote: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
    "3-9": { quote: "It always seems impossible until it’s done.", author: "Nelson Mandela" },
    "3-10": { quote: "You become what you believe.", author: "Oprah Winfrey" },
    // More months (April to December) will follow this same structure, continuing with quotes and authors for each day.
        // March 11th to 31st
        "3-11": { quote: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
    "3-12": { quote: "Your limitation—it's only your imagination.", author: "Unknown" },
    "3-13": { quote: "Great things never come from comfort zones.", author: "Unknown" },
    "3-14": { quote: "Dream it. Wish it. Do it.", author: "Unknown" },
    "3-15": { quote: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
    "3-16": { quote: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
    "3-17": { quote: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
    "3-18": { quote: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
    "3-19": { quote: "Do something today that your future self will thank you for.", author: "Unknown" },
    "3-20": { quote: "Little things make big days.", author: "Unknown" },
    "3-21": { quote: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
    "3-22": { quote: "Don’t wait for opportunity. Create it.", author: "Unknown" },
    "3-23": { quote: "Sometimes we’re tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
    "3-24": { quote: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
    "3-25": { quote: "Dream bigger. Do bigger.", author: "Unknown" },
    "3-26": { quote: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
    "3-27": { quote: "Keep going. Everything you need will come to you at the perfect time.", author: "Unknown" },
    "3-28": { quote: "The harder you work, the luckier you get.", author: "Gary Player" },
    "3-29": { quote: "The man who has confidence in himself gains the confidence of others.", author: "Hasidic Proverb" },
    "3-30": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "3-31": { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },

    // April 1st to 30th
    "4-1": { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    "4-2": { quote: "In the end, we only regret the chances we didn’t take.", author: "Lewis Carroll" },
    "4-3": { quote: "Failure is the condiment that gives success its flavor.", author: "Truman Capote" },
    "4-4": { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    "4-5": { quote: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "4-6": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    "4-7": { quote: "Don’t raise your voice, improve your argument.", author: "Desmond Tutu" },
    "4-8": { quote: "Successful people do what unsuccessful people are not willing to do.", author: "Jim Rohn" },
    "4-9": { quote: "What seems to us as bitter trials are often blessings in disguise.", author: "Oscar Wilde" },
    "4-10": { quote: "If you are not willing to risk the usual, you will have to settle for the ordinary.", author: "Jim Rohn" },
    "4-11": { quote: "The biggest risk is not taking any risk.", author: "Mark Zuckerberg" },
    "4-12": { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    "4-13": { quote: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
    "4-14": { quote: "Don’t let yesterday take up too much of today.", author: "Will Rogers" },
    "4-15": { quote: "It’s not whether you get knocked down, it’s whether you get up.", author: "Vince Lombardi" },
    "4-16": { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    "4-17": { quote: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis" },
    "4-18": { quote: "Your time is limited, so don’t waste it living someone else’s life.", author: "Steve Jobs" },
    "4-19": { quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
    "4-20": { quote: "Action is the foundational key to all success.", author: "Pablo Picasso" },
    "4-21": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "4-22": { quote: "Don’t count the days, make the days count.", author: "Muhammad Ali" },
    "4-23": { quote: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats" },
    "4-24": { quote: "What we achieve inwardly will change outer reality.", author: "Plutarch" },
    "4-25": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "4-26": { quote: "You have to learn the rules of the game. And then you have to play better than anyone else.", author: "Albert Einstein" },
    "4-27": { quote: "There are no shortcuts to any place worth going.", author: "Beverly Sills" },
    "4-28": { quote: "Winning isn’t everything, but wanting to win is.", author: "Vince Lombardi" },
    "4-29": { quote: "If you really want to do something, you’ll find a way. If you don’t, you’ll find an excuse.", author: "Jim Rohn" },
    "4-30": { quote: "Our greatest glory is not in never falling, but in rising every time we fall.", author: "Confucius" },

    // May 1st to 31st
    "5-1": { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    "5-2": { quote: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
    "5-3": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "5-4": { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    "5-5": { quote: "Fall seven times, stand up eight.", author: "Japanese Proverb" },
    "5-6": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "5-7": { quote: "Dream big and dare to fail.", author: "Norman Vaughan" },
    "5-8": { quote: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein" },
    "5-9": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "5-10": { quote: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
    "5-11": { quote: "Don’t let what you cannot do interfere with what you can do.", author: "John Wooden" },
    "5-12": { quote: "It’s not whether you get knocked down; it’s whether you get up.", author: "Vince Lombardi" },
    "5-13": { quote: "I never dreamed about success. I worked for it.", author: "Estee Lauder" },
    "5-14": { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    "5-15": { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    "5-16": { quote: "The secret to success is to know something nobody else knows.", author: "Aristotle Onassis" },
    "5-17": { quote: "If you’re going through hell, keep going.", author: "Winston Churchill" },
    "5-18": { quote: "Do not be embarrassed by your failures, learn from them and start again.", author: "Richard Branson" },
    "5-19": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "5-20": { quote: "Opportunities multiply as they are seized.", author: "Sun Tzu" },
    "5-21": { quote: "Success depends upon previous preparation, and without such preparation there is sure to be failure.", author: "Confucius" },
    "5-22": { quote: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    "5-23": { quote: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs" },
    "5-24": { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    "5-25": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    "5-26": { quote: "Success is stumbling from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "5-27": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },

        // May 28th to 31st
    "5-28": { quote: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
    "5-29": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "5-30": { quote: "Don’t be pushed by your problems. Be led by your dreams.", author: "Ralph Waldo Emerson" },
    "5-31": { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },

    // June 1st to 30th
    "6-1": { quote: "Courage is resistance to fear, mastery of fear—not absence of fear.", author: "Mark Twain" },
    "6-2": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "6-3": { quote: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
    "6-4": { quote: "Success consists of going from failure to failure without loss of enthusiasm.", author: "Winston Churchill" },
    "6-5": { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    "6-6": { quote: "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.", author: "Orison Swett Marden" },
    "6-7": { quote: "Failure is success in progress.", author: "Albert Einstein" },
    "6-8": { quote: "Success is a journey, not a destination.", author: "Ben Sweetland" },
    "6-9": { quote: "Perseverance is not a long race; it is many short races one after another.", author: "Walter Elliot" },
    "6-10": { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    "6-11": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "6-12": { quote: "Patience, persistence, and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
    "6-13": { quote: "It does not matter how slowly you go, as long as you do not stop.", author: "Confucius" },
    "6-14": { quote: "You don’t have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
    "6-15": { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    "6-16": { quote: "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", author: "James Cameron" },
    "6-17": { quote: "Success isn't just about what you accomplish in your life; it's about what you inspire others to do.", author: "Unknown" },
    "6-18": { quote: "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.", author: "Jim Rohn" },
    "6-19": { quote: "Failure is not the opposite of success; it’s part of success.", author: "Arianna Huffington" },
    "6-20": { quote: "Don't be afraid to fail. Be afraid not to try.", author: "Michael Jordan" },
    "6-21": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "6-22": { quote: "Keep your face always toward the sunshine—and shadows will fall behind you.", author: "Walt Whitman" },
    "6-23": { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    "6-24": { quote: "Success is best when it’s shared.", author: "Howard Schultz" },
    "6-25": { quote: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", author: "Jordan Belfort" },
    "6-26": { quote: "Success isn't overnight. It's when every day you get a little better than the day before. It all adds up.", author: "Dwayne Johnson" },
    "6-27": { quote: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein" },
    "6-28": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "6-29": { quote: "The road to success and the road to failure are almost exactly the same.", author: "Colin R. Davis" },
    "6-30": { quote: "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better.", author: "Jim Rohn" },

    // July 1st to 31st
    "7-1": { quote: "There is no elevator to success; you have to take the stairs.", author: "Zig Ziglar" },
    "7-2": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "7-3": { quote: "Success means doing the best we can with what we have. Success is the doing, not the getting; in the trying, not the triumph.", author: "Zig Ziglar" },
    "7-4": { quote: "Success is not measured by money or power or social rank. Success is measured by your discipline and inner peace.", author: "Mike Ditka" },
    "7-5": { quote: "It always seems impossible until it's done.", author: "Nelson Mandela" },
    "7-6": { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    "7-7": { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    "7-8": { quote: "The secret of success is to do the common thing uncommonly well.", author: "John D. Rockefeller Jr." },
    "7-9": { quote: "Success is achieved and maintained by those who try and keep trying.", author: "W. Clement Stone" },
    "7-10": { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    "7-11": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "7-12": { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    "7-13": { quote: "Success is a state of mind. If you want success, start thinking of yourself as a success.", author: "Joyce Brothers" },
    "7-14": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "7-15": { quote: "To succeed in life, you need two things: ignorance and confidence.", author: "Mark Twain" },
    "7-16": { quote: "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome.", author: "Booker T. Washington" },
    "7-17": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "7-18": { quote: "Success comes from having dreams that are bigger than your fears.", author: "Terry Litwiller" },
    "7-19": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "7-20": { quote: "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.", author: "Unknown" },
    "7-21": { quote: "To succeed in life, you need three things: a wishbone, a backbone, and a funny bone.", author: "Reba McEntire" },
    "7-22": { quote: "Success is never accidental.", author: "Jack Dorsey" },
    "7-23": { quote: "There is no substitute for hard work.", author: "Thomas Edison" },
    "7-24": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "7-25": { quote: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
    "7-26": { quote: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs" },
    "7-27": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    "7-28": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "7-29": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "7-30": { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    "7-31": { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    "8-1": { quote: "Don’t watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
    "8-2": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "8-3": { quote: "You miss 100% of the shots you don’t take.", author: "Wayne Gretzky" },
    "8-4": { quote: "I attribute my success to this: I never gave or took any excuse.", author: "Florence Nightingale" },
    "8-5": { quote: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
    "8-6": { quote: "Success seems to be connected with action. Successful people keep moving.", author: "Conrad Hilton" },
    "8-7": { quote: "The secret of success is to do the common things uncommonly well.", author: "John D. Rockefeller Jr." },
    "8-8": { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    "8-9": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    "8-10": { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    "8-11": { quote: "There is no elevator to success, you have to take the stairs.", author: "Zig Ziglar" },
    "8-12": { quote: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
    "8-13": { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    "8-14": { quote: "Success is not about the destination, it’s about the journey.", author: "Zig Ziglar" },
    "8-15": { quote: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "8-16": { quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt" },
    "8-17": { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    "8-18": { quote: "Don’t be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    "8-19": { quote: "Success is 1% inspiration, 99% perspiration.", author: "Thomas Edison" },
    "8-20": { quote: "The secret of success is to know something nobody else knows.", author: "Aristotle Onassis" },
    "8-21": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "8-22": { quote: "Opportunities don’t happen. You create them.", author: "Chris Grosser" },
    "8-23": { quote: "The road to success is always under construction.", author: "Lily Tomlin" },
    "8-24": { quote: "Success is a state of mind. If you want success, start thinking of yourself as a success.", author: "Joyce Brothers" },
    "8-25": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "8-26": { quote: "It is better to fail in originality than to succeed in imitation.", author: "Herman Melville" },
    "8-27": { quote: "Success doesn’t just come and find you, you have to go out and get it.", author: "Unknown" },
    "8-28": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "8-29": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "8-30": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "8-31": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },

    // September 1st to 30th
    "9-1": { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    "9-2": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "9-3": { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    "9-4": { quote: "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.", author: "Jim Rohn" },
    "9-5": { quote: "It does not matter how slowly you go, as long as you do not stop.", author: "Confucius" },
    "9-6": { quote: "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do.", author: "Unknown" },
    "9-7": { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    "9-8": { quote: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
    "9-9": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "9-10": { quote: "Success is a journey, not a destination.", author: "Ben Sweetland" },
    "9-11": { quote: "The secret to success is constancy to purpose.", author: "Benjamin Disraeli" },
    "9-12": { quote: "The harder the conflict, the more glorious the triumph.", author: "Thomas Paine" },
    "9-13": { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    "9-14": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "9-15": { quote: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "9-16": { quote: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    "9-17": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "9-18": { quote: "Success isn’t about how much money you make, it’s about the difference you make in people’s lives.", author: "Michelle Obama" },
    "9-19": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "9-20": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "9-21": { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    "9-22": { quote: "Success is a state of mind. If you want success, start thinking of yourself as a success.", author: "Joyce Brothers" },
    "9-23": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "9-24": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "9-25": { quote: "Success is not measured by what you accomplish, but by the opposition you have encountered, and the courage with which you have maintained the struggle against overwhelming odds.", author: "Orison Swett Marden" },
    "9-26": { quote: "Success consists of going from failure to failure without loss of enthusiasm.", author: "Winston Churchill" },
    "9-27": { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    "9-28": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    "9-29": { quote: "Success isn’t about being the best. It’s about always getting better.", author: "Unknown" },
    "9-30": { quote: "Success is not about the destination; it's a journey.", author: "Zig Ziglar" },
        // October 1st to 31st
        "10-1": { quote: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "10-2": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "10-3": { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    "10-4": { quote: "The best revenge is massive success.", author: "Frank Sinatra" },
    "10-5": { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    "10-6": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "10-7": { quote: "The secret to success is constancy to purpose.", author: "Benjamin Disraeli" },
    "10-8": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "10-9": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "10-10": { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    "10-11": { quote: "You cannot swim for new horizons until you have courage to lose sight of the shore.", author: "William Faulkner" },
    "10-12": { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    "10-13": { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    "10-14": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "10-15": { quote: "Success is not measured by what you accomplish, but by the opposition you have encountered.", author: "Orison Swett Marden" },
    "10-16": { quote: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    "10-17": { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    "10-18": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "10-19": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "10-20": { quote: "Success is liking yourself, liking what you do, and liking how you do it.", author: "Maya Angelou" },
    "10-21": { quote: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "10-22": { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    "10-23": { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    "10-24": { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    "10-25": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "10-26": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "10-27": { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    "10-28": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "10-29": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "10-30": { quote: "Success is not measured by what you accomplish, but by the opposition you have encountered.", author: "Orison Swett Marden" },
    "10-31": { quote: "Success is a journey, not a destination.", author: "Arthur Ashe" },

    // November 1st to 30th
    "11-1": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "11-2": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "11-3": { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    "11-4": { quote: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer" },
    "11-5": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    "11-6": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "11-7": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "11-8": { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    "11-9": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "11-10": { quote: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
    "11-11": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "11-12": { quote: "The secret of success is constancy to purpose.", author: "Benjamin Disraeli" },
    "11-13": { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    "11-14": { quote: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    "11-15": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "11-16": { quote: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "11-17": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "11-18": { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    "11-19": { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    "11-20": { quote: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "11-21": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "11-22": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "11-23": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "11-24": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "11-25": { quote: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    "11-26": { quote: "The secret to success is constancy to purpose.", author: "Benjamin Disraeli" },
    "11-27": { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    "11-28": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "11-29": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "11-30": { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },

    // December 1st to 31st
    "12-1": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "12-2": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "12-3": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "12-4": { quote: "The secret to success is constancy to purpose.", author: "Benjamin Disraeli" },
    "12-5": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "12-6": { quote: "The only way to achieve the impossible is to believe it is possible.", author: "Charles Kingsleigh" },
    "12-7": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "12-8": { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    "12-9": { quote: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
    "12-10": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "12-11": { quote: "Success is a journey, not a destination.", author: "Arthur Ashe" },
    "12-12": { quote: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "12-13": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "12-14": { quote: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
    "12-15": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "12-16": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "12-17": { quote: "Success is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
    "12-18": { quote: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt" },
    "12-19": { quote: "Success is not final, failure is not fatal: It is the courage to continue that counts.", author: "Winston Churchill" },
    "12-20": { quote: "Success is not about the destination; it’s about the journey.", author: "Zig Ziglar" },
    "12-21": { quote: "The secret to success is constancy to purpose.", author: "Benjamin Disraeli" },
    "12-22": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "12-23": { quote: "Success is how high you bounce when you hit bottom.", author: "George S. Patton" },
    "12-24": { quote: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
    "12-25": { quote: "Success is getting what you want. Happiness is wanting what you get.", author: "Dale Carnegie" },
    "12-26": { quote: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
    "12-27": { quote: "The only limit to our realization of tomorrow is our doubts of today.", author: "Franklin D. Roosevelt" },
    "12-28": { quote: "Success is not in what you have, but who you are.", author: "Bo Bennett" },
    "12-29": { quote: "Success is the sum of small efforts, repeated day in and day out.", author: "Robert Collier" },
    "12-30": { quote: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
    "12-31": { quote: "The best way to predict your future is to create it.", author: "Peter Drucker" },





    };
    const dailyBibleVerses = {
    // January 1-31
    "1-1": { verse: "In the beginning, God created the heavens and the earth.", reference: "Genesis 1:1" },
    "1-2": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
    "1-3": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
    "1-4": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
    "1-5": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
    "1-6": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
    "1-7": { verse: "The earth is the Lord’s, and everything in it.", reference: "Psalm 24:1" },
    "1-8": { verse: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.", reference: "Galatians 5:22" },
    "1-9": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
    "1-10": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
    "1-11": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
    "1-12": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
    "1-13": { verse: "And we know that in all things God works for the good of those who love him.", reference: "Romans 8:28" },
    "1-14": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
    "1-15": { verse: "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", reference: "Romans 6:23" },
    "1-16": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
    "1-17": { verse: "Blessed are the meek, for they will inherit the earth.", reference: "Matthew 5:5" },
    "1-18": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
    "1-19": { verse: "The Lord makes firm the steps of the one who delights in him.", reference: "Psalm 37:23" },
    "1-20": { verse: "Come to me, all you who are weary and burdened, and I will give you rest.", reference: "Matthew 11:28" },
    "1-21": { verse: "I have loved you with an everlasting love.", reference: "Jeremiah 31:3" },
    "1-22": { verse: "For we live by faith, not by sight.", reference: "2 Corinthians 5:7" },
    "1-23": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
    "1-24": { verse: "For I am the Lord who heals you.", reference: "Exodus 15:26" },
    "1-25": { verse: "Thanks be to God for his indescribable gift!", reference: "2 Corinthians 9:15" },
    "1-26": { verse: "I am the good shepherd. The good shepherd lays down his life for the sheep.", reference: "John 10:11" },
    "1-27": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
    "1-28": { verse: "The Lord is my shepherd; I lack nothing.", reference: "Psalm 23:1" },
    "1-29": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
    "1-30": { verse: "I have told you these things, so that in me you may have peace.", reference: "John 16:33" },
    "1-31": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },

    // February 1-28
    "2-1": { verse: "The Lord your God is with you, the Mighty Warrior who saves.", reference: "Zephaniah 3:17" },
    "2-2": { verse: "The Lord is a refuge for the oppressed, a stronghold in times of trouble.", reference: "Psalm 9:9" },
    "2-3": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
    "2-4": { verse: "He heals the brokenhearted and binds up their wounds.", reference: "Psalm 147:3" },
    "2-5": { verse: "The Lord is my light and my salvation; whom shall I fear?", reference: "Psalm 27:1" },
    "2-6": { verse: "For the Lord gives wisdom; from his mouth come knowledge and understanding.", reference: "Proverbs 2:6" },
    "2-7": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
    "2-8": { verse: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil.", reference: "Jeremiah 29:11" },
    "2-9": { verse: "Let all that you do be done in love.", reference: "1 Corinthians 16:14" },
    "2-10": { verse: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", reference: "Ephesians 4:32" },
    "2-11": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
    "2-12": { verse: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.", reference: "Isaiah 26:3" },
    "2-13": { verse: "Blessed are those who are persecuted because of righteousness, for theirs is the kingdom of heaven.", reference: "Matthew 5:10" },
    "2-14": { verse: "And we know that in all things God works for the good of those who love him.", reference: "Romans 8:28" },
    "2-15": { verse: "Let everything that has breath praise the Lord.", reference: "Psalm 150:6" },
    "2-16": { verse: "He gives strength to the weary and increases the power of the weak.", reference: "Isaiah 40:29" },
    "2-17": { verse: "The Lord is my shepherd, I lack nothing.", reference: "Psalm 23:1" },
    "2-18": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
    "2-19": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
    "2-20": { verse: "For we live by faith, not by sight.", reference: "2 Corinthians 5:7" },
    "2-21": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
    "2-22": { verse: "The Lord is good to those whose hope is in him, to the one who seeks him.", reference: "Lamentations 3:25" },
    "2-23": { verse: "You are the light of the world. A town built on a hill cannot be hidden.", reference: "Matthew 5:14" },
    "2-24": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
    "2-25": { verse: "The Lord is my light and my salvation; whom shall I fear?", reference: "Psalm 27:1" },
    "2-26": { verse: "For I am the Lord who heals you.", reference: "Exodus 15:26" },
    "2-27": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
    "2-28": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
// March 1-31
        "3-1": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "3-2": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
        "3-3": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
        "3-4": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "3-5": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "3-6": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
        "3-7": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
        "3-8": { verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
        "3-9": { verse: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.", reference: "Galatians 5:22" },
        "3-10": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "3-11": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
        "3-12": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
        "3-13": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
        "3-14": { verse: "I have loved you with an everlasting love.", reference: "Jeremiah 31:3" },
        "3-15": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
        "3-16": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "3-17": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
        "3-18": { verse: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil.", reference: "Jeremiah 29:11" },
        "3-19": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
        "3-20": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "3-21": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
        "3-22": { verse: "For we live by faith, not by sight.", reference: "2 Corinthians 5:7" },
        "3-23": { verse: "The Lord is my light and my salvation; whom shall I fear?", reference: "Psalm 27:1" },
        "3-24": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
        "3-25": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
        "3-26": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
        "3-27": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
        "3-28": { verse: "The Lord your God is with you, the Mighty Warrior who saves.", reference: "Zephaniah 3:17" },
        "3-29": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
        "3-30": { verse: "Let all that you do be done in love.", reference: "1 Corinthians 16:14" },
        "3-31": { verse: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.", reference: "Ephesians 3:20" },
    
        // April 1-30
        "4-1": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "4-2": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
        "4-3": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
        "4-4": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "4-5": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "4-6": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
        "4-7": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
        "4-8": { verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
        "4-9": { verse: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness.", reference: "Galatians 5:22" },
        "4-10": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "4-11": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
        "4-12": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
        "4-13": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
        "4-14": { verse: "I have loved you with an everlasting love.", reference: "Jeremiah 31:3" },
        "4-15": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
        "4-16": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "4-17": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
        "4-18": { verse: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil.", reference: "Jeremiah 29:11" },
        "4-19": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
        "4-20": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "4-21": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
        "4-22": { verse: "For we live by faith, not by sight.", reference: "2 Corinthians 5:7" },
        "4-23": { verse: "The Lord is my light and my salvation; whom shall I fear?", reference: "Psalm 27:1" },
        "4-24": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
        "4-25": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
        "4-26": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
        "4-27": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
        "4-28": { verse: "The Lord your God is with you, the Mighty Warrior who saves.", reference: "Zephaniah 3:17" },
        "4-29": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
        "4-30": { verse: "Let all that you do be done in love.", reference: "1 Corinthians 16:14" },
        "5-1": { verse: "The Lord is my shepherd; I lack nothing.", reference: "Psalm 23:1" },
        "5-2": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
        "5-3": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "5-4": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "5-5": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
        "5-6": { verse: "For the Lord your God is with you wherever you go.", reference: "Joshua 1:9" },
        "5-7": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "5-8": { verse: "And we know that in all things God works for the good of those who love him.", reference: "Romans 8:28" },
        "5-9": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "5-10": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
        "5-11": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
        "5-12": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
        "5-13": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
        "5-14": { verse: "For we live by faith, not by sight.", reference: "2 Corinthians 5:7" },
        "5-15": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
        "5-16": { verse: "Let all that you do be done in love.", reference: "1 Corinthians 16:14" },
        "5-17": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
        "5-18": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
        "5-19": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
        "5-20": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
        "5-21": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
        "5-22": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
        "5-23": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
        "5-24": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
        "5-25": { verse: "You are the light of the world. A town built on a hill cannot be hidden.", reference: "Matthew 5:14" },
        "5-26": { verse: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil.", reference: "Jeremiah 29:11" },
        "5-27": { verse: "The Lord is with you wherever you go.", reference: "Joshua 1:9" },
        "5-28": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "5-29": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "5-30": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
        "5-31": { verse: "In the beginning was the Word, and the Word was with God, and the Word was God.", reference: "John 1:1" },
    
        // June 1-30
        "6-1": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "6-2": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
        "6-3": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "6-4": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "6-5": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
        "6-6": { verse: "For the Lord your God is with you wherever you go.", reference: "Joshua 1:9" },
        "6-7": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
        "6-8": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "6-9": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
        "6-10": { verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
        "6-11": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
        "6-12": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "6-13": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
        "6-14": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
        "6-15": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
        "6-16": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
        "6-17": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
        "6-18": { verse: "I have loved you with an everlasting love.", reference: "Jeremiah 31:3" },
        "6-19": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "6-20": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
        "6-21": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
        "6-22": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "6-23": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
        "6-24": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
        "6-25": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
        "6-26": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
        "6-27": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "6-28": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "6-29": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "6-30": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "7-1": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "7-2": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
        "7-3": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "7-4": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "7-5": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
        "7-6": { verse: "For the Lord your God is with you wherever you go.", reference: "Joshua 1:9" },
        "7-7": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
        "7-8": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "7-9": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
        "7-10": { verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
        "7-11": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
        "7-12": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "7-13": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
        "7-14": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
        "7-15": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
        "7-16": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
        "7-17": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
        "7-18": { verse: "I have loved you with an everlasting love.", reference: "Jeremiah 31:3" },
        "7-19": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "7-20": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
        "7-21": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
        "7-22": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "7-23": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
        "7-24": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
        "7-25": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
        "7-26": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
        "7-27": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "7-28": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "7-29": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "7-30": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "7-31": { verse: "In the beginning was the Word, and the Word was with God, and the Word was God.", reference: "John 1:1" },
    
        // August 1-31
        "8-1": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "8-2": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
        "8-3": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "8-4": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "8-5": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
        "8-6": { verse: "For the Lord your God is with you wherever you go.", reference: "Joshua 1:9" },
        "8-7": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
        "8-8": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "8-9": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
        "8-10": { verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
        "8-11": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
        "8-12": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "8-13": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
        "8-14": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
        "8-15": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
        "8-16": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
        "8-17": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
        "8-18": { verse: "I have loved you with an everlasting love.", reference: "Jeremiah 31:3" },
        "8-19": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "8-20": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
        "8-21": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
        "8-22": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "8-23": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
        "8-24": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
        "8-25": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
        "8-26": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
        "8-27": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "8-28": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "8-29": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "8-30": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "8-31": { verse: "In the beginning was the Word, and the Word was with God, and the Word was God.", reference: "John 1:1" },
        "9-1": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "9-2": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
        "9-3": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "9-4": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "9-5": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
        "9-6": { verse: "For the Lord your God is with you wherever you go.", reference: "Joshua 1:9" },
        "9-7": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
        "9-8": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "9-9": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
        "9-10": { verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
        "9-11": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
        "9-12": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "9-13": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
        "9-14": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
        "9-15": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
        "9-16": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
        "9-17": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
        "9-18": { verse: "I have loved you with an everlasting love.", reference: "Jeremiah 31:3" },
        "9-19": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "9-20": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
        "9-21": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
        "9-22": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "9-23": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
        "9-24": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
        "9-25": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
        "9-26": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
        "9-27": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "9-28": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "9-29": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "9-30": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
    
        // October 1-31
        "10-1": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "10-2": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
        "10-3": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "10-4": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "10-5": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
        "10-6": { verse: "For the Lord your God is with you wherever you go.", reference: "Joshua 1:9" },
        "10-7": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
        "10-8": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "10-9": { verse: "The Lord is my shepherd; I shall not want.", reference: "Psalm 23:1" },
        "10-10": { verse: "Blessed are the poor in spirit, for theirs is the kingdom of heaven.", reference: "Matthew 5:3" },
        "10-11": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
        "10-12": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "10-13": { verse: "For I know the plans I have for you, declares the Lord.", reference: "Jeremiah 29:11" },
        "10-14": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
        "10-15": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
        "10-16": { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
        "10-17": { verse: "The Lord is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
        "10-18": { verse: "I have loved you with an everlasting love.", reference: "Jeremiah 31:3" },
        "10-19": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "10-20": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
        "10-21": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
        "10-22": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "10-23": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
        "10-24": { verse: "For the word of the Lord is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
        "10-25": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
        "10-26": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
        "10-27": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
        "10-28": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
        "10-29": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
        "10-30": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
        "10-31": { verse: "In the beginning was the Word, and the Word was with God, and the Word was God.", reference: "John 1:1" },
            // November 1-30
    "11-1": { verse: "The Lord is my shepherd; I lack nothing.", reference: "Psalm 23:1" },
    "11-2": { verse: "He gives strength to the weary and increases the power of the weak.", reference: "Isaiah 40:29" },
    "11-3": { verse: "I will not leave you as orphans; I will come to you.", reference: "John 14:18" },
    "11-4": { verse: "You are the light of the world. A town built on a hill cannot be hidden.", reference: "Matthew 5:14" },
    "11-5": { verse: "For God did not give us a spirit of timidity, but a spirit of power, of love and of self-discipline.", reference: "2 Timothy 1:7" },
    "11-6": { verse: "Be strong and courageous. Do not be afraid; do not be discouraged.", reference: "Joshua 1:9" },
    "11-7": { verse: "The Lord will bless you and keep you; the Lord will make his face shine upon you and be gracious to you.", reference: "Numbers 6:24-25" },
    "11-8": { verse: "And we know that in all things God works for the good of those who love him.", reference: "Romans 8:28" },
    "11-9": { verse: "The Lord is my light and my salvation; whom shall I fear?", reference: "Psalm 27:1" },
    "11-10": { verse: "I have come that they may have life, and have it to the full.", reference: "John 10:10" },
    "11-11": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
    "11-12": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
    "11-13": { verse: "The Lord is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
    "11-14": { verse: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", reference: "Philippians 1:6" },
    "11-15": { verse: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.", reference: "Philippians 4:19" },
    "11-16": { verse: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", reference: "Philippians 4:6" },
    "11-17": { verse: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.", reference: "Jeremiah 29:11" },
    "11-18": { verse: "Let all that you do be done in love.", reference: "1 Corinthians 16:14" },
    "11-19": { verse: "The joy of the Lord is your strength.", reference: "Nehemiah 8:10" },
    "11-20": { verse: "For where your treasure is, there your heart will be also.", reference: "Matthew 6:21" },
    "11-21": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
    "11-22": { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
    "11-23": { verse: "The name of the Lord is a strong tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
    "11-24": { verse: "The Lord is good to those whose hope is in him, to the one who seeks him.", reference: "Lamentations 3:25" },
    "11-25": { verse: "The Lord is my refuge and my fortress, my God, in whom I trust.", reference: "Psalm 91:2" },
    "11-26": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
    "11-27": { verse: "The Lord is my light and my salvation—whom shall I fear?", reference: "Psalm 27:1" },
    "11-28": { verse: "For the Lord is righteous, he loves justice; the upright will see his face.", reference: "Psalm 11:7" },
    "11-29": { verse: "I will bless the Lord at all times; his praise shall continually be in my mouth.", reference: "Psalm 34:1" },
    "11-30": { verse: "The Lord is good to those who hope is in him, to the one who seeks him.", reference: "Lamentations 3:25" },

    // December 1-31
    "12-1": { verse: "In the beginning was the Word, and the Word was with God, and the Word was God.", reference: "John 1:1" },
    "12-2": { verse: "The Word became flesh and made his dwelling among us.", reference: "John 1:14" },
    "12-3": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
    "12-4": { verse: "I am the way and the truth and the life.", reference: "John 14:6" },
    "12-5": { verse: "Peace I leave with you; my peace I give you.", reference: "John 14:27" },
    "12-6": { verse: "You will seek me and find me when you seek me with all your heart.", reference: "Jeremiah 29:13" },
    "12-7": { verse: "The Lord is my shepherd; I lack nothing.", reference: "Psalm 23:1" },
    "12-8": { verse: "He gives strength to the weary and increases the power of the weak.", reference: "Isaiah 40:29" },
    "12-9": { verse: "The Lord is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
    "12-10": { verse: "For God so loved the world that he gave his one and only Son.", reference: "John 3:16" },
    "12-11": { verse: "Trust in the Lord with all your heart and lean not on your own understanding.", reference: "Proverbs 3:5" },
    "12-12": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
    "12-13": { verse: "The joy of the Lord is your strength.", reference: "Nehemiah 8:10" },
    "12-14": { verse: "The Lord will fight for you; you need only to be still.", reference: "Exodus 14:14" },
    "12-15": { verse: "The Lord is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
    "12-16": { verse: "The Lord is my light and my salvation; whom shall I fear?", reference: "Psalm 27:1" },
    "12-17": { verse: "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.", reference: "Jeremiah 29:11" },
    "12-18": { verse: "Let all that you do be done in love.", reference: "1 Corinthians 16:14" },
    "12-19": { verse: "For where your treasure is, there your heart will be also.", reference: "Matthew 6:21" },
    "12-20": { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
    "12-21": { verse: "The Lord is gracious and righteous; our God is full of compassion.", reference: "Psalm 116:5" },
    "12-22": { verse: "The name of the Lord is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
    "12-23": { verse: "Peace I leave with you; my peace I give you.", reference: "John 14:27" },
    "12-24": { verse: "For unto us a child is born, to us a son is given.", reference: "Isaiah 9:6" },
    "12-25": { verse: "Glory to God in the highest, and on earth peace to men on whom his favor rests.", reference: "Luke 2:14" },
    "12-26": { verse: "I am the Alpha and the Omega, the First and the Last, the Beginning and the End.", reference: "Revelation 22:13" },
    "12-27": { verse: "For God has not given us a spirit of fear, but of power and of love and of a sound mind.", reference: "2 Timothy 1:7" },
    "12-28": { verse: "I can do all things through Christ who strengthens me.", reference: "Philippians 4:13" },
    "12-29": { verse: "For the Lord is good and his love endures forever; his faithfulness continues through all generations.", reference: "Psalm 100:5" },
    "12-30": { verse: "The Lord is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
    "12-31": { verse: "The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you.", reference: "Numbers 6:24-25" }
        
        
};

